<?php
/** @var \Andriy\Points\Block\Widget\PointsList $block */
?>
<?php
$points = $block->getPointsCollection();
?>
<?php foreach ($points as $point): ?>
    <div>
        <a onclick="initMap('<?php echo $point->getLatitude(); ?>','<?php echo $point->getlongitude(); ?>')">
            <?php echo $point->getName(); ?>
            <?php echo $point->getLacation(); ?>
            <?php echo $point->getAddress(); ?>
            <?php echo $point->getLatitude(); ?>
            <?php echo $point->getlongitude(); ?>
            <?php echo $block->getShipping($point->getData('shipping_id')); ?>

        </a>
    </div>

<?php endforeach; ?>
<?php if ($block->getApi()): ?>
    <div id="map"></div>
    <script
        src="https://maps.googleapis.com/maps/api/js?key=<?php echo $block->getApi() ?>&callback=initMap&v=weekly"
        defer
    ></script>
<?php endif ?>
<script type="text/x-magento-init" xml="space">
        {
          "*": {
                  "slider" : "Andriy_Points/js/map"
                }
        }

</script>

